### ISSUE TITLE
Windows 7 - Crashes on typing more than 11 letters in search field

### ISSUE THREAD

**Issue by ljgww** [cpbotha/nvpy#102]
I am user of nvAlt on Mac, and I was looking for Windows solution, found this and very glad to find it! It is not ugly, it is beautiful!

My problem is that I am used on nvAlt to type title in search, and when nvAlt do not find it it automatically creates a new note for me.

When I do it in nvpy it simply exits (looks like crash but there is no message). At first I thought I am typing too fast but it is simply a size that matters :)

**Comment by kinesin** [comment]
Same for me. Otherwise no problems, but shuts down after a couple of keystrokes in the serach field.

Windows 10, 64bit
Python 2.7.10, 64bit
new nvpy installation via pip-install
modified nvpy.cfg to save as text files.

**Comment by yuuki0xff** [comment]
This issue is too old.  Latest stable version is fixed many bugs.  Please use the latest version.

If this problem still persists, reopen it again.
