### ISSUE TITLE
stopped syncing

### ISSUE THREAD

**Issue by federvar** [cpbotha/nvpy#108]
nvpy stopped syncing out of the blue!! I have no idea and googling for a fix is to no avail! I'm I the only one? any help?

**Comment by CheriPai** [comment]
This happened to be, but I got it to sync again by deleting all the files in the directory: ~/.nvpy
*** Make sure you backup all your notes before trying this ***

**Comment by yuuki0xff** [comment]
This issue is too old.  Latest stable version is fixed many bugs.  Please use the latest version.

If this problem still persists, reopen it again.
