### ISSUE TITLE
node-webkit port

### ISSUE THREAD

**Issue by patcon** [cpbotha/nvpy#112]
I understand that this would be a *massive* task not to be undertaken lightly, but wondering whether it's something you'd find interesting. Seems like it might best allow a revamp of the UI in a cross-platform manner, if so desired.

It's technically written in node, but can manage python processes by shelling out

- [Simple node-webkit app serving simple python app](http://blog.infireal.com/wsgi-node-webkit-2014-03.html)

*Full disclosure: the effort would unfortunately not be forthcoming from myself, so it's just an inquiry.*

**Comment by cpbotha** [comment]
Although generally I think there's lots to be said for using the  browser as the UI, for nvpy I'd rather spend time on making the tiny tkinter interface more attractive. (there is the simplenote web-app after all :)
