### ISSUE TITLE
ctrl-D to delete should require a confirmation

### ISSUE THREAD

**Issue by jcstroud** [cpbotha/nvpy#119]
I accidentally hit ctrl-D and the note was gone.

Nuf said.

**Comment by cpbotha** [comment]
The note is still there: You can undelete via the simplenote web interface.

I have to think about either such a warning dialog, or an undo option right in nvpy itself. (the note is not really deleted locally either, only a flag is set)

**Comment by cwchaney** [comment]
+1 ... ctrl-D is hardwired in my brain to delete a line.

**Comment by LeHack** [comment]
+1 I also got myself caught by this, and since I use nvpy only locally, I wasn't able to undelete it.

**Comment by cpbotha** [comment]
I'll put in that confirmation dialog. Handling undelete across all different modes of operation (thanks @LeHack for the reminder) is a bit much now, and deletion is mostly not something that happens THAT often.

**Comment by cpbotha** [comment]
Fixed in a8172bae4d3493145199a91267f5fc404837319b
