### ISSUE TITLE
Choose where to sync to

### ISSUE THREAD

**Issue by 3arn0wl** [cpbotha/nvpy#128]
The nvPY client has a killer feature missing: the ability to choose the directory to which the database auto-saves: Simplenote server, HD, private/public cloud.

**Comment by jkall** [comment]
Isn't this issue fixed already? You can choose directory by the variable "db_path" in config file nvpy.cfg

**Comment by cpbotha** [comment]
You can configure the local directory containing your notes. You can enable / disable syncing with simplenote servers. Therefore I am closing this issue.

(thank you @jkall)
