### ISSUE TITLE
Tag support

### ISSUE THREAD

**Issue by dmych** [cpbotha/nvpy#13]
Any chance to get tag support, as it work on Simplenote webapp?

**Comment by pihentagy** [comment]
Any update on the taglist feature? Is there a tag browser/autocompleter?

**Comment by yuuki0xff** [comment]
The tag browser is already implemented. You can see all tags by [Tools] -> [List tags] in the top menu.
Tag autocomplete feature currently does not exist. But I feel that it is necessary. So I will try to implement the autocomplete feature on the weekend.
