### ISSUE TITLE
Reproducible sync error on update_note

### ISSUE THREAD

**Issue by cpbotha** [cpbotha/nvpy#130]
To reproduce:
- edit note, then exit nvpy before the changes can sync to the server
- restart nvpy, as part of phase 1 of the syncing, it'll try to update the note to server
- this fails with a HTTP 412 error, `precondition failed`
- you can work around this by exiting nvpy, deleting only the offending note, then restarting nvpy.

![image](https://cloud.githubusercontent.com/assets/937871/11930610/b4d72176-a7ed-11e5-8d0a-6343c6b33126.png)

**Comment by cpbotha** [comment]
Apparently 412 is returned during throttling. Could be that this issue is transient, will check later.

**Comment by yuuki0xff** [comment]
The workaround has been added.
