### ISSUE TITLE
Internet address containing round brackets

### ISSUE THREAD

**Issue by roscho** [cpbotha/nvpy#135]
I believe that I may have stumbled upon a minor bug to do with internet links where I have found that a link with brackets '()' included fails to open the correct page in a web browser. I note that the link when inserted in nvpy contents the link is highlighted up to the '(' only and fails to activate the full link when clicked.
Try example link: http://msdn.microsoft.com/en-us/library/aa752574(VS.85).aspx

**Comment by cpbotha** [comment]
I manually pulled in your fix and gave credit, thanks! 2c7b66dd975f5314a0534471507284c7e499b284

(I hope we have not broken any other uses cases. I don't have tests for this either. :(
