### ISSUE TITLE
Multiple nvpy instances?

### ISSUE THREAD

**Issue by crazzyfool** [cpbotha/nvpy#139]
Hi,

I have two simplenote accounts (with different emails addresses) - is it possible, and if so, how can I install two instances to nvpy to run at the same time?  At the moment, I need to quit and then edit my .nvpy.cfg before restarting.

I am using Arch Linux and installed manually with git.

**Comment by LeHack** [comment]
You can just use the --cfg and create two aliases, each with a specific path to the correct config file.
It was added for exactly such purpose.

**Comment by cpbotha** [comment]
Thank you @LeHack ! Closing this issue.
