### ISSUE TITLE
Change path on windows?

### ISSUE THREAD

**Issue by jazzgroove** [cpbotha/nvpy#140]
On the Windows version, is there a way to change the notes path to an alternate directory besides .nvpy?

**Comment by adisaurabh** [comment]
+ 1. Would be great to have this. I could choose a dropbox/onedrive folder so that the notes are also online and available on other devices. I do not want to use simplenote.

**Comment by yuuki0xff** [comment]
That function is already implemented. Please try to edit your nvpy.cfg like this.
```
[nvpy]
db_path = C:\Users\username\Dropbox\nvpy\
text_path = C:\Users\username\Dropbox\nvpy\notes
```
