### ISSUE TITLE
do not leave note while editing

### ISSUE THREAD

**Issue by weaselbox** [cpbotha/nvpy#156]
While attempting to fix some notes where characters like < > & etc are displayed as html entities (I swear I've seen that issue mentioned here but can't find it now), I've encountered a problem with nvpy suddenly booting me out of the note I was editing before I can complete the replacement.

Steps: search for &lt;

find &lt; in note, start backspacing out &lt;  (selecting the whole search term seems impossible)

suddenly the note disappears (presumably because it no longer contains the search string) and you're who knows where.

**Comment by yuuki0xff** [comment]
This issue was caused by broken change of legacy simplenote api last year.  See #157
Currently, nvpy has been switched to simperium api, so this problem was solved.
