### ISSUE TITLE
">" uploaded and then downloaded by a second nvpy becomes "&gt;"

### ISSUE THREAD

**Issue by alusiani** [cpbotha/nvpy#157]
Hi,

when I use nvpy to update a note, and I insert a ">" character, the note is uploaded to simplenote. If I use a second nvpy client and "synch full" to get all updates, the ">" character becomes the html sequence "&gt;".

Cheers,

**Comment by qualitymanifest** [comment]
I am having this issue as well. In my experience, it does not have to be written in nvpy to have this formatting problem when synced on another nvpy client - it can be written in simplenote, but when synced on an nvpy client you get this html entity conversion. Nvpy then saves it this way, so if you go and view it on simplenote again, you get `&gt;`, `&lt;`, `&amp;`, etc.

Version is 1.0.0+git20171203.c91062c-1

**Comment by yuuki0xff** [comment]
Sorry for my late response. This problem was fixed in 9a8eaf2.
