### ISSUE TITLE
nvPy (sometimes) crashes on rendering Markdown

### ISSUE THREAD

**Issue by FrancoisMalan** [cpbotha/nvpy#16]
On my Windows7 setup (running Python 2.7 32bit) nvPy sometimes (intermittently?) crashes on rendering Markdown (Ctrl-M).
Usually preceded my not doing anything when requesting Markdown rendering. If repeatedly requesting it, it crashes.
After restarting nvPy it worked.

**Comment by yuuki0xff** [comment]
This issue is too old. Latest stable version is fixed many bugs. Please use the latest version.

If this problem still persists, reopen it again.
