### ISSUE TITLE
Notes unreadable when using dark system theme

### ISSUE THREAD

**Issue by grandfso** [cpbotha/nvpy#163]
Hi there,
I'm running debian testing based ditro with Mate desktop. I am running a dark system theme and have issue with readability in nvPY. The font and background seem to be selectively applying my theme settings (lighter font) but the background reamains white.

I tried to set background = black / yellow / green etc. in .nvpy.cfg but it does not seem to work. Font size settings are picked up. 

Screenshot: https://i.imgur.com/jjzf8xe.png

**Comment by crazzyfool** [comment]
Yeah I have the same issue.  Its almost impossible to read!  Not sure where its pulling this light grey from!?

**Comment by yuuki0xff** [comment]
Please set the `background_color` option.  It will change the background color of note list on left side and note editor on right side.
```
# ~/.nvpy.cfg
background_color = black
```

**Comment by crazzyfool** [comment]
That's a lot more usable now, thanks.  However still far from perfect.  I now can hardly read the selected title on the left and I have no idea where my keyboard cursor is on the right.  The only way to know is to type something lol :-(

![selection_009](https://user-images.githubusercontent.com/10143249/50644339-75454480-0f68-11e9-8b33-e5d2927bb43b.png)

**Comment by crazzyfool** [comment]
Yeah sure.  I'm using the i3 community version of Manjaro.  What information can I provide you with over and above?

**Comment by yuuki0xff** [comment]
Thanks.  That's good enough.  I'm installing it.

**Comment by yuuki0xff** [comment]
I'm added some options in ce2d3543a301b3eaf3f6bd057b076994c76af48d to change colors.  In nvpy-example.cfg, I have written examples of light theme and dark theme.  Please try it.

# Light Theme (default)
![2019-01-04-063047_1912x990_scrot](https://user-images.githubusercontent.com/7306559/50663160-188b6d80-0fec-11e9-9b8d-2268bd97c6b5.png)
https://github.com/cpbotha/nvpy/blob/master/nvpy/nvpy-example.cfg#L97-L104

# Dark Theme
![2019-01-04-063345_1912x990_scrot](https://user-images.githubusercontent.com/7306559/50663161-188b6d80-0fec-11e9-8434-22102798f553.png)
https://github.com/cpbotha/nvpy/blob/master/nvpy/nvpy-example.cfg#L106-L113

**Comment by crazzyfool** [comment]
Wow that's awesome!  Much better!!

![nvpy_012](https://user-images.githubusercontent.com/10143249/50681077-fb619980-1001-11e9-91c2-c76d55be9498.png)

Thanks yuuki!!

**Comment by grandfso** [comment]
@yuuki0xff thank you :)
