### ISSUE TITLE
Text too light

### ISSUE THREAD

**Issue by crazzyfool** [cpbotha/nvpy#170]
The text is too light I can hardly read it.  How can this be changed?

![nvpy_008](https://user-images.githubusercontent.com/10143249/50587437-d8a27a00-0e75-11e9-958e-7d5605b2c680.png)

**Comment by crazzyfool** [comment]
Is there a "font_color=black" setting I can add to ~/.nvpy.cfg for example?  Not sure where its getting this light grey colour from?!

**Comment by yuuki0xff** [comment]
Duplicate of #163
