### ISSUE TITLE
Windows Defender false positive

### ISSUE THREAD

**Issue by jnsl** [cpbotha/nvpy#186]
![image](https://user-images.githubusercontent.com/1777928/62006741-0c602c80-b145-11e9-993a-047635ea2a33.png)

**Comment by yuuki0xff** [comment]
I reported to this issue to Microsoft Security Intelligence.
https://www.microsoft.com/en-us/wdsi/submission/aa00c778-fcf8-4a44-9232-254a07851dc4

**Comment by yuuki0xff** [comment]
> Analyst comments:
>  We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.
>  1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
> 
> Thank you for contacting Microsoft.
