### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by jasondavis** [cpbotha/nvpy#21]
Please update readme with information on how to use this on a Windows PC

**Comment by sergeevabc** [comment]
Since 1.1.0 was released 4 days ago, @cpbotha, consider rolling out Windows binary for mere users, please.

**Comment by yuuki0xff** [comment]
@sergeevabc Thank you for your proposal.  I decided to provide the standalone binary for windows users.  You can get exe file from https://github.com/cpbotha/nvpy/releases/tag/v1.2.0
