### ISSUE TITLE
More than one Simplenote email?

### ISSUE THREAD

**Issue by BoVandenberg** [cpbotha/nvpy#214]
With two clear uses for the program, can I run two email addresses? ie. work@simplenote & play@simplenote...

Great program. I hope it bounces back!!

**Comment by yuuki0xff** [comment]
Thanks for using nvpy! If you create two config files and start nvpy with `--cfg` command-line option, you will be able to use two accounts at the same time.

For example, create the following two configuration files like below ...

```
# ~/.nvpy-work.cfg
[nvpy]
sn_username = work@simplenote
sn_password = xxxxxx
db_path = /home/your-user-name/.nvpy-work
```

```
# ~/.nvpy-play.cfg
sn_username = play@simplenote
sn_password = xxxxxx
db_path = /home/your-user-name/.nvpy-play
# IMPORTANT: the db_path option should specify the different directory.
```

And execute the following commands.  You will be able to start two nvpy processes with different accounts.

```
$ nvpy --cfg ~/.nvpy-work.cfg
$ nvpy --cfg ~/.nvpy-play.cfg
```
