### ISSUE TITLE
Sync Errors

### ISSUE THREAD

**Issue by toolmanz** [cpbotha/nvpy#217]
Please see attached. Problem with syncing. It keeps adding the same notes multiple times. It quits after saying ok.

Windows host Simplenote works fine except it too has added all the duplicate notes.

Running on Linux Mint in Oracle VM running on Windows 10 Host.

![Unexpected Error_005](https://user-images.githubusercontent.com/35659872/102935297-dfb45f80-4473-11eb-8ec8-a8fe53858981.png)

**Comment by yuuki0xff** [comment]
Thank you for the bug report.

This error occurs by data race in the notes_db. I knew this issue, but I forgot to fix it. I will fix it during winter vacation.

**Comment by toolmanz** [comment]
Excellent....

A very good and useful program. Kudos...

Tim


-------- Original Message --------

**Comment by yuuki0xff** [comment]
I added mitigations for this issue in 844e8e5ad67cbae91603e95703b5fc34e78675ab. Reopen it if this issue recurs.
