### ISSUE TITLE
UI issue: Titlebar is black

### ISSUE THREAD

**Issue by arrrlaska** [cpbotha/nvpy#220]
I'm trying to figure out why nvpy is showing up with a fairly ugly white-on-black titlebar. It's not on any of the screenshots I see on the project page, and playing with the color settings and theme doesn't seem to have any effect.

At first, I thought something was messed up with my *g*tk theme, but then realized nvpy only uses Tk.

Any ideas how to make the menus black-on-white?

Thanks.

![2021-08-27-105111_972x611_scrot](https://user-images.githubusercontent.com/38673813/131155835-6eeeda58-5654-4380-ab5b-b9424ea99416.png)

**Comment by yuuki0xff** [comment]
Thank you for reporting the issue.

Not just the menu bar. The border color (?) of the status bar is also black. I seems that the default color of some UI components is black in your environment.

I would like to investigate. Could you tell me the following information:

- OS name and version
- nvPY version
- Notable settings for nvPY and OS

**Comment by arrrlaska** [comment]
Hi! Here's some basic system info: https://url.privatepastebin.com/2g

Versions:
```
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.1.1
Codename:	Pahvo
$ uname -rm
5.10.60-1-MANJARO x86_64
$ pacman -Qi nvpy |head -5
Name            : nvpy
Version         : 2.1.0-2
Description     : Simplenote syncing note-taking application, but uglier and cross-platformerer.
Architecture    : any
URL             : https://github.com/cpbotha/nvpy
```

(It also says nvpy 2.10 within the app)

Dependencies' versions:
```
$ pacman -Qi $(pacman -Qi nvpy |grep ^Depends.On |cut -f2 -d:) |grep -e ^Name -e ^Version
Name            : python
Version         : 3.9.6-1
Name            : python-docutils
Version         : 0.17.1-1
Name            : python-markdown
Version         : 3.3.4-1
Name            : python-setuptools
Version         : 1:57.4.0-1
Name            : python-simplenote
Version         : 2.1.4-1
Name            : tk
Version         : 8.6.11.1-1
```

My nvpy config: https://url.privatepastebin.com/2h

Note: my config is kept in a ccrypt-encrypted file, and is only left unencrypted on ram-based tmp storage momentarily as the program is started. However, I've tried decrypting the config onto disk, and I get the same result.

Please let me know what other info I can provide to be helpful.

Much thanks!

**Comment by arrrlaska** [comment]
More background: My desktop environment (window manager, really) is i3-gaps, which is pretty minimalistic.
I also have a laptop running i3-gaps, and nvpy looks the same there.
I have another laptop running i3-gaps as well, I'll check nvpy there in a couple days.

**Comment by yuuki0xff** [comment]
I succeeded in reproducing your reported issue with the Manjaro Linux i3 edition.

The system seems to have a dark theme by default. Xresouces also define the default background color as dark. You can regain the default behavior by removing `*background` and `*foreground` attributes from Xresouces.

I don't immediately know how to change the background color for just the nvPY. For the time being, please try the following methods. 

```
# ~/.Xresources

# Comment out the default color settings.
#*background: #222d31
#*foreground: #d8d8d8
```

```
# Reload configuration.
xrdb <~/.Xresources
```

**Comment by arrrlaska** [comment]
Looks perfect now, thank you!

I'd be interested if there's a way to set the background and foreground colors for just Tk in .Xresources. I wasn't able to find any leads online.
`Tk*background` didn't work. I even tried `*Tk*ackground*`
