### ISSUE TITLE
Highlight matching file names in search results?

### ISSUE THREAD

**Issue by alpcantal** [cpbotha/nvpy#221]
Presently, nvpy searches the contents of the entire notes and highlights only the contents when a note is activated.

Sometimes, though, when I search a specific file and the search term is coincidentally mentioned _across different files_, the file I'm looking for becomes hard to find and I have to look at each title one by one. It's a small issue, but I'd assume this also generates a lot of friction for others.

Is it possible to highlight matching file names in search results? Thank you

P.S. I don't know anything about programming

**Comment by yuuki0xff** [comment]
nvPY v2.3.0 includes the proposed feature.
