### ISSUE TITLE
Any new release is possible ?

### ISSUE THREAD

**Issue by passionate2023** [cpbotha/nvpy#230]
Any new release is possible ?

**Comment by yuuki0xff** [comment]
I forgot to release the latest changes. I'll publish a new version in a few days.

**Comment by yuuki0xff** [comment]
The release took a while because some issues on the v2.3.0 milestone exist. Now, I'm writing a release note for the new release.

**Comment by passionate2023** [comment]
is v2.3.0 is released and working ??? a simplenote provides the API still for syncing with this tool ? Please kindly confirm

**Comment by yuuki0xff** [comment]
Yes, v2.3.1 is available. See https://github.com/cpbotha/nvpy/releases

If you have problems, please create a new issue.

**Comment by passionate2023** [comment]
a simplenote provides the API still for syncing with this tool ? Please kindly confirm

**Comment by yuuki0xff** [comment]
Yes, it should work. At least, nvPY can sync with simplenote on my computers. No serious issues have been found.

**Comment by passionate2023** [comment]
My simplenote account cannot be shared as simplenote doesn't have read-only access. So how to sync without providing my credentials to anyone?
