### ISSUE TITLE
nostr support?

### ISSUE THREAD

**Issue by ghost** [cpbotha/nvpy#239]

**Comment by yuuki0xff** [comment]
Synchronization logic implemented at `NotesDB.sync_*()` methods. The NotesDB class also has several functions, such as local storage access and data filtering.

In many places, the note is represented by dict type. The contents of the dict are based on the Simplenote specification. It will be easier to understand if you look at the data stored in `~/.nvpy/*.json`. I would like to migrate from dict to the Note class, but I don't have the time to do it :-(

If you want to implement it quickly,

1. Create the NostrNotesDB class inherits NotesDB class.
2. Implement a plugin mechanism that allows us to select the NotesDB class to be used.
