### ISSUE TITLE
npy CLI

### ISSUE THREAD

**Issue by minthemiddle** [cpbotha/nvpy#42]
There currently does not exist any Simplenote CLI client that really works. There is a VIM plugin (https://github.com/mrtazz/simplenote.vim) and a CLI backup tool (https://github.com/vrillusions/simplenote-cli), but no pure CLI client. 

One branch of nvpy could focus on that instead of tweaking the UI.

**Comment by pataquets** [comment]
Since the issue was opened long time ago, just for documenting:
https://github.com/insanum/sncli
https://github.com/gudnm/gonote

Hope it helps. @minthemiddle: Fancy to close the issue if it's OK?

**Comment by pataquets** [comment]
Disclaimer: never used any of them.
However, if you switch anytime to Emacs, the 'simplenote2' package works perfectly. :wink:
