### ISSUE TITLE
Plans for keychain integration?

### ISSUE THREAD

**Issue by bcomnes** [cpbotha/nvpy#46]
It seems like storing plaintext passwords is never a good idea, yet this is a requirement to perform a sync.  Most modern OS's provide a keychain to avoid having to do this.  Is it possible to integrate the gnome keychain so that storing plaintext passwords isn't required?

**Comment by initiate6** [comment]
Inside nvpy.py I added the following as a dirty way to prompt for password. End goal is to add encryption so the entire directory is encrypted. Once that is completed and everything looks nice I will create a pull request. 

#Prompt dialog for password
from Tkinter import *
import tkSimpleDialog


        #self.sn_password = cp.get(cfg_sec, 'sn_password', raw=True) Not secure
	def getpwd():
		root = Tk()
		try:
			password = tkSimpleDialog.askstring("Password", "Enter password:", show='*')

		except Exception as e:
			print("Error: %s" % e )

		root.destroy()
		root.mainloop()

		return password

	self.sn_password = getpwd()
