### ISSUE TITLE
[ubuntu] nvPY won't quit after a while

### ISSUE THREAD

**Issue by bayonne** [cpbotha/nvpy#48]
If nvPY stays up for hours, I can't always quit it with ctrl+Q , I have to `pkill nvpy'.
This is on Ubuntu 12.04, nvPY 0.9.4

Is anyone else seeing this ?

**Comment by yuuki0xff** [comment]
This issue is too old.  Latest stable version is fixed many bugs.  Please use the latest version.

If this problem still persists, reopen it again.
