### ISSUE TITLE
Main window not displayed correctly while reading notes

### ISSUE THREAD

**Issue by tpeeters** [cpbotha/nvpy#50]
The first time I start nvpy, it needs to download my notes from simplenote, and while it does that, the nvpy window is not displayed correctly.

Check this screenshot - http://www.stack.nl/~timp/nvPY-syncing.png

**Comment by yuuki0xff** [comment]
Since v1.1.0, nvpy supports background full-sync. Recent versions have improved sync speed.
In the current version, this issue have been resolved.
