### ISSUE TITLE
Crashes while typing in search field

### ISSUE THREAD

**Issue by jon1270** [cpbotha/nvpy#61]
I'm new to both NVPY and Github, so please forgive me if I'm missing something important.  I'm running NVPY on a Windows 7 machine, and it reliably crashes when I type the thirteenth character into the search field.  Behaves just fine with up to 12 characters, but on the 13th character the program closes by itself.  When I restart it, the message 'retrieving full note list from server, could take a while' is displayed for several seconds, during which the program is unresponsive.

**Comment by yuuki0xff** [comment]
This issue is too old. Latest stable version is fixed many bugs. Please use the latest version.

If this problem still persists, reopen it again.
