### ISSUE TITLE
Use pythonw.exe instead of python.exe in the Windows version?

### ISSUE THREAD

**Issue by ClairelyClaire** [cpbotha/nvpy#63]
Is it possible for nvpy.exe to use pythonw so that there isn't an empty console window running whenever the application is running? I downloaded the regular python files and ran through pythonw that way, but of course this means I can't use the handy upgrade tool to keep the application updated.

Also - is nvpye.exe a fully compiled version of the application like what py2exe can produce? Can it be run without a full python installation?

**Comment by yuuki0xff** [comment]
Since v1.2.0, we provides nvpy.exe (window version) and nvpy-debug.exe (console version).
It take a little while to launch, but your request will be satisfied.
