### ISSUE TITLE
Syncing with simplenote

### ISSUE THREAD

**Issue by helloravi** [cpbotha/nvpy#72]
I get "syncnote step 1 error- could not update note to server". I dont understand what is happening but here are the symptoms

1)I can sync individual notes using "sync current note"
2)If i add a new note to simplenote account through other means. It is not added to nvpy. 

I am confused as to what to do about it. I tried mailing Botha. He is probably busy and hence I am writing it here.

**Comment by yuuki0xff** [comment]
This issue is too old.  Latest stable version is fixed many bugs.  Please use the latest version.

If this problem still persists, reopen it again.
