### ISSUE TITLE
nvPY in Windows replaces file names with character '_' when I really wanted space ' ' 

### ISSUE THREAD

**Issue by magicnemo** [cpbotha/nvpy#83]
Maybe related to Issue #58.

E.g. Write "Instruction - Manual for Markdown" in a new note, when I exit nvAlt it has created Instruction_-_Manual_for_Markdown in the file system.

I found the problem in utils.py, there is a line in function get_note_title_file() saying replace ' ' with '_'. I don't know why, maybe some OS this works on can't handle space in file names?

Solution is to mark this row as a comment, after having done this I don't see the problem again.

```
    # Unchecked below row, don't know why it's useful to mess up file names??
    #fn = fn.replace(' ', '_')
    fn = fn.replace('/', '_') 
```

**Comment by yuuki0xff** [comment]
Added `replace_filename_spaces` option. See #206.
